# Generated by Django 3.2.3 on 2022-06-03 15:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default=None, max_length=200)),
                ('description', models.CharField(default=None, max_length=1000)),
                ('email', models.EmailField(default=None, max_length=254)),
            ],
        ),
    ]
