# Generated by Django 3.2.3 on 2022-06-03 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('description', 'email', 'name')},
        ),
    ]
